version: '2'
services:
  sbp-app:
    image: sbp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sbp-postgresql:5432/sbp
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://sbp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://sbp-elasticsearch:9200
    ports:
      - 8080:8080
  sbp-postgresql:
    extends:
      file: postgresql.yml
      service: sbp-postgresql
  sbp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: sbp-elasticsearch
